apiVersion: batch/v1
kind: Job
metadata:
  namespace: ${NAMESPACE}
  name: ${SYSTEM_NAME}${JOB_TAG}
  labels:
    app: ${SYSTEM_NAME}${JOB_TAG}
    type: ${MODE}
spec:
  template:
    metadata:
      labels:
        app: ${SYSTEM_NAME}${JOB_TAG}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpuType # A5000 or 2080Ti
                operator: In
                values:
                - ${GPU_TYPE}
      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: rw-vol
          persistentVolumeClaim:
            claimName: ${RW_VOLUME}
        - name: ro-vol
          persistentVolumeClaim:
            claimName: ${RO_VOLUME}
      imagePullSecrets:
      - name: ${SECRET}
      containers:
        - name: ${SYSTEM_NAME}
          image: ${REPO_HOST}/${REPO}:${SYSTEM_NAME}-${DUSER}-v${SYSTEM_VERSION}
          workingDir: /workspace
          resources:
            requests:
              memory: ${TOTAL_MEM}Gi
              cpu: ${TOTAL_CPU}
              nvidia.com/gpu: ${NGPU}
            limits:
              memory: ${TOTAL_MEM}Gi
              cpu: ${TOTAL_CPU}
              nvidia.com/gpu: ${NGPU}
          ports:
            - containerPort: 8888
              name: notebook-port
          volumeMounts:
            - name: rw-vol
              subPath: ${DUSER}/code/${K8_SRC_PATH}
              mountPath: /workspace/${SRC_PATH}
            - name: rw-vol
              subPath: ${DUSER}/data
              mountPath: /workspace/data
            - name: rw-vol
              subPath: ${DUSER}/logs
              mountPath: /workspace/logs
            - name: dshm
              mountPath: /dev/shm
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WANDB_API_KEY
              value: ${WANDB_API_KEY}
            - name: SYSTEM_NAME
              value: ${SYSTEM_NAME}
            - name: SYSTEM_VERSION
              value: ${SYSTEM_VERSION}
            - name: SYSTEM_DESCRIPTION
              value: ${SYSTEM_DESCRIPTION}
            - name: CDR_TOKEN
              value: ${CDR_TOKEN}
            - name: CDR_HOST
              value: ${CDR_HOST}
            - name: CALLBACK_URL
              value: ${CALLBACK_URL}
            - name: NGROK_AUTHTOKEN
              value: ${NGROK_AUTHTOKEN}
            - name: NGROK_SECRET
              value: ${NGROK_SECRET}
            - name: NGROK_PORT
              value: "${NGROK_PORT}"
            - name: MODEL_NAME
              value: ${MODEL_NAME}
            - name: MODEL_VERSION
              value: "${MODEL_VERSION}"
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - "tmux send-keys -t server C-c"
