#!/bin/sh
# python sri_maper/src/pretrain.py experiment=h4/natl_ree/exp_ree_maevit_pretrain_natl-v2
# python sri_maper/src/pretrain.py experiment=h4/natl_ree/exp_ree_maevit_pretrain_natl-v3
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-3 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-3 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-3 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-4 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-4 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-5 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-5 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-5 data.multiplier=10
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-3 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-3 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-3 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-4 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-4 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-5 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-5 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-5 data.multiplier=20
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-3 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-3 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-3 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-4 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-4 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-5 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-5 data.multiplier=30
# python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v0 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-05_23-04-50/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-5 data.multiplier=30
#
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-3 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-3 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-3 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-4 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-4 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-5 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-5 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-5 data.multiplier=10
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-3 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-3 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-3 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-4 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-4 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-5 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-5 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-5 data.multiplier=20
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-3 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-3 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-3 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-4 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-4 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-4 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.1,1.0] model.optimizer.lr=1e-5 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.05,1.0] model.optimizer.lr=1e-5 data.multiplier=30
python sri_maper/src/train_test_map.py experiment=h4/natl_ree/exp_ree_maevit_classifier_natl-v3 model.net.backbone_ckpt_embeddings=logs/cmta3-pretrain-maevit/runs/2024-08-14_21-28-14/checkpoints/embeddings_d256.npy trainer=gpu trainer.deterministic=true data.likely_neg_range=[0.02,1.0] model.optimizer.lr=1e-5 data.multiplier=30