_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: null
    window_size: ${data.window_size}
    evidence_layer_paths:
      - null
    label_raster_path:
      - null
