_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/mvt-h3_aoi_1_v2_d${data.window_size}.tif
    raster_files_path: ${paths.data_dir}/raster_libraries/h3_aoi_1_mvt_raster_library
    dilation_size: ${data.window_size}
    raster_files:
      - path: "CEUS_GRAV_Isostatic_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_GRAV_RI_1VD_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_GRAV_RI_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_GRAV_RI_HD_1VD_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_GRAV_RI_HD_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_MAG_DRTP_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_MAG_DRTP_HD_TDR_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_MAG_DRTP_TDR_CEUSSSC_R0_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "CEUS_MAG_TMAG_AAS_CEUSSSC_R0_Log_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geophysics_LAB_HGM_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geophysics_LAB_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geophysics_Mag_RTP_Long-Wavelength_HGM_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geophysics_Moho_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geophysics_LAB_HGM_Worms.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geology_cambrian-to-early-ordovician-carbonates_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "Geology_faults_clipped.tif"
        type: float32
        outlier_removal: false
        normalize: true
      - path: "mvt_leadzinc_deposits_h3_aoi_1.tif"
        type: bool
        outlier_removal: false
        normalize: false
