_target_: sri_maper.src.data.preprocessing.generate_raster_stacks
raster_stacks:
  - raster_stack_path: ${data.tif_dir}/tungsten-skarn-natl.tif
    raster_files_path: ${paths.data_dir}/raster_library
    raster_files:
      - "Geology/Geology_Lithology_Majority_Igneous_Extrusive_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Igneous_Intrusive_Felsic_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Igneous_Intrusive_Mafic_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Metamorphic_Gneiss_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Metamorphic_Gneiss_Paragneiss_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Metamorphic_Schist_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Other_Unconsolidated_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Sedimentary_Chemical_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Majority_Sedimentary_Siliciclastic_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Igneous_Extrusive_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Igneous_Intrusive_Felsic_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Igneous_Intrusive_Mafic_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Metamorphic_Gneiss_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Metamorphic_Gneiss_Paragneiss_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Metamorphic_Schist_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Other_Unconsolidated_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Sedimentary_Chemical_clipped_dilated.tif"
      - "Geology/Geology_Lithology_Minority_Sedimentary_Siliciclastic_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Cambrian_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Cretaceous_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Devonian_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Jurassic_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Mesoproterozoic_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Mississippian_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Neoarchean_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Neogene_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Neoproterozoic_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Ordovician_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Paleogene_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Paleoproterozoic_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Pennsylvanian_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Permian_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Quaternary_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Silurian_clipped_dilated.tif"
      - "Geology/Geology_Period_Maximum_Majority_Triassic_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Cambrian_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Cretaceous_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Devonian_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Jurassic_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Mesoproterozoic_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Mississippian_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Neoarchean_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Neogene_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Neoproterozoic_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Ordovician_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Paleogene_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Paleoproterozoic_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Pennsylvanian_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Permian_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Quaternary_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Silurian_clipped_dilated.tif"
      - "Geology/Geology_Period_Minimum_Majority_Triassic_clipped_dilated.tif"
      - "Geology/Geology_Sedimentary_Dictionaries_clipped_dilated.tif"
      - "Geology/Geology_Igneous_Dictionaries_clipped_dilated.tif"
      - "Geology/Geology_Metamorphic_Dictionaries_clipped_dilated.tif"
      - "Geology/Geology_Paleolatitude_Period_Minimum_clipped_dilated.tif"
      - "Geology/Geology_TerraneBoundaries_Proximity_clipped_dilated.tif"
      - "Geology/Geology_PassiveMargins_Proximity_clipped_dilated.tif"
      - "Geology/Geology_Faults_Proximity_clipped_dilated.tif"
      - "Geophysics/Seismic/Geophysics_LAB_clipped_dilated.tif"
      - "Geophysics/Seismic/Geophysics_Moho_clipped_dilated.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Uranium_clipped_dilated.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Potassium_clipped_dilated.tif"
      - "Geophysics/Radiometric/Geophysics_Radiometric_Thorium_clipped_dilated.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM_clipped_dilated.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_HGM_Worms_clipped_dilated.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_clipped_dilated.tif"
      - "Geophysics/Magnetics/Geophysics_Mag_RTP_Long-Wavelength_HGM_Worms_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_HGM_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_HGM_Worms_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Bouguer_Up30km_HGM_Worms_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Gravity_Isostatic_HGM_clipped_dilated.tif"
      - "Geophysics/Gravity/Geophysics_Satellite_Gravity_clipped_dilated.tif"
      - "Geochemistry/Geochemistry_BlackShales_Proximity_clipped_dilated.tif"
      - "Labels/tungsten_skarn_sites_cont_US_clipped_dilated.tif"
    raster_files_types:
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - bool
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - float32
      - bool