_target_: src.models.cma_module_pretrain_mae.CMALitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-2

scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR
  _partial_: true
  last_epoch: -1

net:
  _target_: src.models.mae_vit.MAE_ViT

# compile model for faster training with pytorch 2.0
compile: false

mc_samples: 100

warmup_epoch: 3