apiVersion: batch/v1
kind: Job
metadata:
  namespace: criticalmaas-ta3
  name: cmaas-ta3-vzdev02
  labels:
    app: cmaas-ta3-vzdev02
    type: run
spec:
  template:
    metadata:
      labels:
        app: cmaas-ta3-vzdev02
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpuType # A5000 or 2080Ti
                operator: In
                values:
                - 2080Ti
              # - key: kubernetes.io/hostname
              #   operator: In
              #   values:
              #   - cse-k8s-cvt-011.k8s.sri.com

      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: rw-vol
          persistentVolumeClaim:
            claimName: criticalmaas-ta3-rw
        - name: ro-vol
          persistentVolumeClaim:
            claimName: criticalmaas-ta3-ro
      imagePullSecrets:
      - name: docker-io-secret
      containers:
        - name: cmaas-ta3
          image: open.docker.sarnoff.com/criticalmaas-ta3:cmaas-ta3-e35547-v0.0

          workingDir: /workspace
          resources:
            requests:
              memory: 40Gi
              cpu: 32
              nvidia.com/gpu: 1
            limits:
              memory: 40Gi
              cpu: 32
              nvidia.com/gpu: 1

          ports: # List of ports to expose from the container (can be forwarded using k9s to local machine)
            - containerPort: 8888
              name: notebook-port

          volumeMounts:
            # Working directory for source code
            - name: rw-vol
              subPath: e35547/code/dev/src
              mountPath: /workspace/src

            # Working directory for config files
            - name: rw-vol
              subPath: e35547/code/dev/configs
              mountPath: /workspace/configs
            
            # Working directory for scripts
            - name: rw-vol
              subPath: e35547/code/dev/scripts
              mountPath: /workspace/scripts
            
            # shared directory for storing data
            - name: ro-vol
              subPath: data
              mountPath: /workspace/data

            # Working directory for checkpoints, output, etc.
            - name: rw-vol
              subPath: e35547/logs
              mountPath: /workspace/logs

            # Virtual memory
            - name: dshm
              mountPath: /dev/shm

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WANDB_API_KEY
              value: b99742ace87c41d1ae02445bd9df9d3bf4c5066e
